// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTaskList.Data;

namespace WebApiTaskList.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210813081355_InitialNew")]
    partial class InitialNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("WebApiTaskList.Models.ListModel", b =>
                {
                    b.Property<int>("ListModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ListModelId");

                    b.ToTable("List");
                });

            modelBuilder.Entity("WebApiTaskList.Models.TaskModel", b =>
                {
                    b.Property<int>("TaskModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListModelForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskModelId");

                    b.HasIndex("ListModelForeignKey");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("WebApiTaskList.Models.TaskModel", b =>
                {
                    b.HasOne("WebApiTaskList.Models.ListModel", "ListModel")
                        .WithMany("TaskModels")
                        .HasForeignKey("ListModelForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListModel");
                });

            modelBuilder.Entity("WebApiTaskList.Models.ListModel", b =>
                {
                    b.Navigation("TaskModels");
                });
#pragma warning restore 612, 618
        }
    }
}
